version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    networks:
      - public
      - private
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: mysql:5.7.34
    volumes:
      - dbstore:/var/lib/mysql
    networks:
      - private
    environment:
      MYSQL_ROOT_PASSWORD: rootpswd
      MYSQL_DATABASE: demodb
      MYSQL_USER: demouser
      MYSQL_PASSWORD: demopswd

volumes:
  dbstore:

networks:
  public:
  private:
